#!/bin/bash
# This script works only under the current directory.
# It deletes symlinks and their associated data directories.
# To avoid any catastrophical event, deletable symlinks must begin with Data/, followed by some project name, followed by 6 digits, followed by -, followed by 4 digits.
regex='^Data/.+\-20[0-9]{6}-[0-9]{4}(-[0-9])?$'
for i in "$@"
do
    if [[ $i =~ $regex && -L $i ]]; then # -L checks symlink
        rm -rf $( cd $i && pwd -P )
        rm $i
    else
        echo "Ignored deleteion of $i"
    fi
done