#! /bin/bash
# -H forces to output filename even there is only one match
grep -H -e ".*" .stages/*/journal.txt -r | \
    awk '\
BEGIN{ journal = ""; }\
 { \
size = index($1,"journal.txt") + length("journal.txt");
this_journal = substr($1,1,size); \
if( this_journal != journal ) { \
if ( journal != "" ) print ""; \
printf "-----  %s  -----\n" , this_journal; \
}\
journal = this_journal; \
printf "\t%s\n",  substr($0, size+1 ); \
 }'
