#!/bin/bash
name=$1
if [[ -d $name ]]; then
    echo "ERROR: $name already exists."
    exit 1
else
    mkdir $name
fi

if [ $? -ne 0 ]; then
    echo "Lab $name incomplete. Code 0001"
    exit 1
fi

top_dir=$(pwd)

cd $name

# create default stuff
ln -s $top_dir/stage $(pwd)/stage
ln -s $top_dir/delrun $(pwd)/delrun
ln -s $top_dir/jnl $(pwd)/jnl
ln -s $top_dir/comment $(pwd)/comment
ln -s $top_dir/vw $(pwd)/vw
ln -s $top_dir/diskusage $(pwd)/diskusage
ln -s $top_dir/.subtrees/Buick/buick $(pwd)/buick
cp $top_dir/examples/CMakeLists.txt $top_dir/examples/pic.hpp $(pwd)/
sed -i "s/project(.*)/project(\"$1\")/" $(pwd)/CMakeLists.txt # this line sets the project name in CMakeLists.txt

if [ $? -ne 0 ]; then
    echo "Lab $name incomplete. Code 0002"
    exit 1
fi

# printf "%s\n" \
#        "set(LAB_SHADOWS \"\")"\
#        "set(LAB_NAME \"$name\")"\
#        "list(APPEND LAB_SHADOWS \"UserControl.cpp\")"\
#        > src/CMakeLists.txt

# if [ $? -ne 0 ]; then
#     echo "Lab $name incomplete. Code 0004"
#     exit 1
# fi

echo -e "\e[1mLab $name\e[0m is successfully created."
