#! /bin/bash
tnow=`date +%F-%H-%M-%S`
project_name=${PWD##*/} # the current direcoty name. copied from https://stackoverflow.com/questions/1371261/get-current-directory-name-without-full-path-in-a-bash-script

skeleton_file=".skeleton$tnow"
printf "%s" "# Please enter the message for the current run. To abort, simply exit and don't save this file." > $skeleton_file

vim_before=".vim_before$tnow"
printf "%s" "autocmd BufNewFile * 0read ${skeleton_file}" > $vim_before

vim_after=".vim_after$tnow"
printf "%s\n" \
       "set number" \
       "normal 2G" \
       "startinsert" \
       > $vim_after

message_file=".message$tnow"
vim $message_file --cmd "source ${vim_before}" -c "source ${vim_after}"
rm $skeleton_file
rm $vim_before
rm $vim_after

if [[ -f $message_file ]]; then
    message=`tail -n "+2" $message_file`
    rm $message_file
else
    echo "Job not staged."
    exit 0
fi

stage_dir=".stages"
if [[ ! -d $stage_dir ]]; then
    mkdir $stage_dir
fi

while [[ -d $stage_dir/$tnow ]]; do
    tnow=${tnow}x
done

oe_dir=`pwd`/oe # need an abosulte path
if [[ ! -d $oe_dir ]]; then
    mkdir $oe_dir
fi

mkdir $stage_dir/$tnow
mkdir $stage_dir/$tnow/bin
cp CMakeLists.txt pic.hpp gen.hpp $stage_dir/$tnow/
cp bin/pic $stage_dir/$tnow/bin/

if [[ -f job.sh ]]; then
    cp job.sh $stage_dir/$tnow/
fi

cd $stage_dir/$tnow
exec 5>&1 # save stdout of current session to fd5
jobID=$( echo "$@" |tee >(cat - >&5))

journal_file="journal.txt"
printf "%s\n" \
       "Project := $project_name"\
       "StageTime := $tnow"\
       "Message := $message"\
       "JobID := $jobID"\
       > $journal_file
