#! /bin/bash
root=$(git rev-parse --show-toplevel) # the top dir of Pigeon
journal=$($root/.pgn/pick $1)
ret=$?
if [[ $ret != 0 ]]; then # check return code
    exit $ret
fi

# add comment to journal.txt. Open with vim, place cursor to last line. If no "Comment :", first create it
vim_after=".vim_comment"
printf "%s\n" \
       'if !search("Comment := ")' \
       '    execute "normal! GoComment := "' \
       'endif' \
       'execute "normal! $"' \
       > $vim_after
vim $journal -S $vim_after
rm $vim_after

# copy this journal file to DataDir if existed
datadir=$(grep "DataDir := " $journal -r)
datadir=${datadir:$(expr length "DataDir := ")} # substring ${substr:position:length}
if [[ $datadir == "" ]]; then
    echo "DataDir not existed. Skip copying journal."
else
    cp $journal $datadir
fi
