#! /bin/bash
arr=($(grep -l "$1" .stages/*/journal.txt -r)) # convert space-separated string to array
size=${#arr[@]}
if (( size == 0 )); then
    echo "ERROR : no matched journal.txt. Note that filenames are not matched against." >&2
    exit 1
elif (( size > 1 )); then
    if [[ "$1" == "" ]]; then # if $1 is missing, open the last one
        echo ${arr[-1]} # last element
        exit 0
    else
        echo "ERROR : matched more than 1 journal.txt" >&2
        echo ${arr[@]} >&2
        exit 1
    fi
else
    echo ${arr[0]}
    exit 0
fi
